name: Flask CI

on:
  push:
    branches: [ text-crud, main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout reposito
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set enviroment variables
        run: |
          echo "FLASK_APP=app.py" >> $GITHUB_ENV
          echo "FLASK_ENV=testing" >> $GITHUB_ENV
          echo "DATABASE_URL=sqlite:///test.db" >> $GITHUB_ENV

      - name: Run database migrations
        run: |
          flask db upgrade
